"""schema integrity and performance fixes

Revision ID: 131a05b9332f
Revises: e449aae6105e
Create Date: 2026-05-16 18:10:16.930368

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '131a05b9332f'
down_revision: Union[str, Sequence[str], None] = 'e449aae6105e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_col_data_quality_stat_date'), 'col_data_quality', ['stat_date'], unique=False)
    op.create_unique_constraint('uq_data_quality', 'col_data_quality', ['meter_id', 'stat_date'])
    op.drop_constraint(op.f('col_data_quality_meter_id_fkey'), 'col_data_quality', type_='foreignkey')
    op.drop_constraint(op.f('col_data_quality_task_id_fkey'), 'col_data_quality', type_='foreignkey')
    op.create_foreign_key(None, 'col_data_quality', 'dev_meter', ['meter_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'col_data_quality', 'col_task', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_reading_lookup', 'col_meter_reading', ['meter_id', 'point_id', 'reading_time'], unique=False)
    op.drop_constraint(op.f('col_meter_reading_task_id_fkey'), 'col_meter_reading', type_='foreignkey')
    op.drop_constraint(op.f('col_meter_reading_meter_id_fkey'), 'col_meter_reading', type_='foreignkey')
    op.drop_constraint(op.f('col_meter_reading_point_id_fkey'), 'col_meter_reading', type_='foreignkey')
    op.create_foreign_key(None, 'col_meter_reading', 'col_task', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'col_meter_reading', 'dev_meter', ['meter_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'col_meter_reading', 'dev_meter_point', ['point_id'], ['id'], ondelete='RESTRICT')
    op.create_unique_constraint('uq_reading_daily', 'col_reading_daily', ['meter_id', 'point_id', 'stat_date'])
    op.drop_constraint(op.f('col_reading_daily_point_id_fkey'), 'col_reading_daily', type_='foreignkey')
    op.drop_constraint(op.f('col_reading_daily_meter_id_fkey'), 'col_reading_daily', type_='foreignkey')
    op.create_foreign_key(None, 'col_reading_daily', 'dev_meter_point', ['point_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'col_reading_daily', 'dev_meter', ['meter_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_col_task_next_execute_time'), 'col_task', ['next_execute_time'], unique=False)
    op.create_index('ix_task_schedule', 'col_task', ['is_enabled', 'next_execute_time'], unique=False)
    op.drop_constraint(op.f('col_task_created_by_fkey'), 'col_task', type_='foreignkey')
    op.create_foreign_key(None, 'col_task', 'sys_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('col_task_device', 'error_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('col_task_device_log_id_fkey'), 'col_task_device', type_='foreignkey')
    op.drop_constraint(op.f('col_task_device_task_id_fkey'), 'col_task_device', type_='foreignkey')
    op.drop_constraint(op.f('col_task_device_meter_id_fkey'), 'col_task_device', type_='foreignkey')
    op.create_foreign_key(None, 'col_task_device', 'col_task_log', ['log_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'col_task_device', 'dev_meter', ['meter_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'col_task_device', 'col_task', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('col_task_log', 'error_message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('col_task_log_task_id_fkey'), 'col_task_log', type_='foreignkey')
    op.create_foreign_key(None, 'col_task_log', 'col_task', ['task_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_dev_meter_project_id'), 'dev_meter', ['project_id'], unique=False)
    op.drop_constraint(op.f('dev_meter_created_by_fkey'), 'dev_meter', type_='foreignkey')
    op.drop_constraint(op.f('dev_meter_meter_type_id_fkey'), 'dev_meter', type_='foreignkey')
    op.drop_constraint(op.f('dev_meter_project_id_fkey'), 'dev_meter', type_='foreignkey')
    op.create_foreign_key(None, 'dev_meter', 'dev_meter_type', ['meter_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dev_meter', 'dev_project', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dev_meter', 'sys_user', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('dev_meter_attachment_uploaded_by_fkey'), 'dev_meter_attachment', type_='foreignkey')
    op.create_foreign_key(None, 'dev_meter_attachment', 'sys_user', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('dev_meter_borrow_lab_approver_id_fkey'), 'dev_meter_borrow', type_='foreignkey')
    op.drop_constraint(op.f('dev_meter_borrow_meter_id_fkey'), 'dev_meter_borrow', type_='foreignkey')
    op.drop_constraint(op.f('dev_meter_borrow_dept_approver_id_fkey'), 'dev_meter_borrow', type_='foreignkey')
    op.drop_constraint(op.f('dev_meter_borrow_borrower_id_fkey'), 'dev_meter_borrow', type_='foreignkey')
    op.create_foreign_key(None, 'dev_meter_borrow', 'dev_meter', ['meter_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'dev_meter_borrow', 'sys_user', ['lab_approver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dev_meter_borrow', 'sys_user', ['dept_approver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'dev_meter_borrow', 'sys_user', ['borrower_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_dev_meter_point_obis_code'), table_name='dev_meter_point')
    op.create_unique_constraint('uq_meter_point_obis', 'dev_meter_point', ['meter_id', 'obis_code'])
    op.drop_constraint(op.f('dev_meter_point_meter_id_fkey'), 'dev_meter_point', type_='foreignkey')
    op.create_foreign_key(None, 'dev_meter_point', 'dev_meter', ['meter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('dev_meter_repair', 'cost',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_constraint(op.f('dev_meter_repair_repaired_by_fkey'), 'dev_meter_repair', type_='foreignkey')
    op.drop_constraint(op.f('dev_meter_repair_meter_id_fkey'), 'dev_meter_repair', type_='foreignkey')
    op.create_foreign_key(None, 'dev_meter_repair', 'dev_meter', ['meter_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'dev_meter_repair', 'sys_user', ['repaired_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('dev_meter_status_changed_by_fkey'), 'dev_meter_status', type_='foreignkey')
    op.create_foreign_key(None, 'dev_meter_status', 'sys_user', ['changed_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_sys_audit_log_created_at'), 'sys_audit_log', ['created_at'], unique=False)
    op.create_foreign_key(None, 'sys_permission', 'sys_permission', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sys_permission', type_='foreignkey')
    op.drop_index(op.f('ix_sys_audit_log_created_at'), table_name='sys_audit_log')
    op.drop_constraint(None, 'dev_meter_status', type_='foreignkey')
    op.create_foreign_key(op.f('dev_meter_status_changed_by_fkey'), 'dev_meter_status', 'sys_user', ['changed_by'], ['id'])
    op.drop_constraint(None, 'dev_meter_repair', type_='foreignkey')
    op.drop_constraint(None, 'dev_meter_repair', type_='foreignkey')
    op.create_foreign_key(op.f('dev_meter_repair_meter_id_fkey'), 'dev_meter_repair', 'dev_meter', ['meter_id'], ['id'])
    op.create_foreign_key(op.f('dev_meter_repair_repaired_by_fkey'), 'dev_meter_repair', 'sys_user', ['repaired_by'], ['id'])
    op.alter_column('dev_meter_repair', 'cost',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'dev_meter_point', type_='foreignkey')
    op.create_foreign_key(op.f('dev_meter_point_meter_id_fkey'), 'dev_meter_point', 'dev_meter', ['meter_id'], ['id'])
    op.drop_constraint('uq_meter_point_obis', 'dev_meter_point', type_='unique')
    op.create_index(op.f('ix_dev_meter_point_obis_code'), 'dev_meter_point', ['obis_code'], unique=False)
    op.drop_constraint(None, 'dev_meter_borrow', type_='foreignkey')
    op.drop_constraint(None, 'dev_meter_borrow', type_='foreignkey')
    op.drop_constraint(None, 'dev_meter_borrow', type_='foreignkey')
    op.drop_constraint(None, 'dev_meter_borrow', type_='foreignkey')
    op.create_foreign_key(op.f('dev_meter_borrow_borrower_id_fkey'), 'dev_meter_borrow', 'sys_user', ['borrower_id'], ['id'])
    op.create_foreign_key(op.f('dev_meter_borrow_dept_approver_id_fkey'), 'dev_meter_borrow', 'sys_user', ['dept_approver_id'], ['id'])
    op.create_foreign_key(op.f('dev_meter_borrow_meter_id_fkey'), 'dev_meter_borrow', 'dev_meter', ['meter_id'], ['id'])
    op.create_foreign_key(op.f('dev_meter_borrow_lab_approver_id_fkey'), 'dev_meter_borrow', 'sys_user', ['lab_approver_id'], ['id'])
    op.drop_constraint(None, 'dev_meter_attachment', type_='foreignkey')
    op.create_foreign_key(op.f('dev_meter_attachment_uploaded_by_fkey'), 'dev_meter_attachment', 'sys_user', ['uploaded_by'], ['id'])
    op.drop_constraint(None, 'dev_meter', type_='foreignkey')
    op.drop_constraint(None, 'dev_meter', type_='foreignkey')
    op.drop_constraint(None, 'dev_meter', type_='foreignkey')
    op.create_foreign_key(op.f('dev_meter_project_id_fkey'), 'dev_meter', 'dev_project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('dev_meter_meter_type_id_fkey'), 'dev_meter', 'dev_meter_type', ['meter_type_id'], ['id'])
    op.create_foreign_key(op.f('dev_meter_created_by_fkey'), 'dev_meter', 'sys_user', ['created_by'], ['id'])
    op.drop_index(op.f('ix_dev_meter_project_id'), table_name='dev_meter')
    op.drop_constraint(None, 'col_task_log', type_='foreignkey')
    op.create_foreign_key(op.f('col_task_log_task_id_fkey'), 'col_task_log', 'col_task', ['task_id'], ['id'])
    op.alter_column('col_task_log', 'error_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'col_task_device', type_='foreignkey')
    op.drop_constraint(None, 'col_task_device', type_='foreignkey')
    op.drop_constraint(None, 'col_task_device', type_='foreignkey')
    op.create_foreign_key(op.f('col_task_device_meter_id_fkey'), 'col_task_device', 'dev_meter', ['meter_id'], ['id'])
    op.create_foreign_key(op.f('col_task_device_task_id_fkey'), 'col_task_device', 'col_task', ['task_id'], ['id'])
    op.create_foreign_key(op.f('col_task_device_log_id_fkey'), 'col_task_device', 'col_task_log', ['log_id'], ['id'])
    op.alter_column('col_task_device', 'error_message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'col_task', type_='foreignkey')
    op.create_foreign_key(op.f('col_task_created_by_fkey'), 'col_task', 'sys_user', ['created_by'], ['id'])
    op.drop_index('ix_task_schedule', table_name='col_task')
    op.drop_index(op.f('ix_col_task_next_execute_time'), table_name='col_task')
    op.drop_constraint(None, 'col_reading_daily', type_='foreignkey')
    op.drop_constraint(None, 'col_reading_daily', type_='foreignkey')
    op.create_foreign_key(op.f('col_reading_daily_meter_id_fkey'), 'col_reading_daily', 'dev_meter', ['meter_id'], ['id'])
    op.create_foreign_key(op.f('col_reading_daily_point_id_fkey'), 'col_reading_daily', 'dev_meter_point', ['point_id'], ['id'])
    op.drop_constraint('uq_reading_daily', 'col_reading_daily', type_='unique')
    op.drop_constraint(None, 'col_meter_reading', type_='foreignkey')
    op.drop_constraint(None, 'col_meter_reading', type_='foreignkey')
    op.drop_constraint(None, 'col_meter_reading', type_='foreignkey')
    op.create_foreign_key(op.f('col_meter_reading_point_id_fkey'), 'col_meter_reading', 'dev_meter_point', ['point_id'], ['id'])
    op.create_foreign_key(op.f('col_meter_reading_meter_id_fkey'), 'col_meter_reading', 'dev_meter', ['meter_id'], ['id'])
    op.create_foreign_key(op.f('col_meter_reading_task_id_fkey'), 'col_meter_reading', 'col_task', ['task_id'], ['id'])
    op.drop_index('ix_reading_lookup', table_name='col_meter_reading')
    op.drop_constraint(None, 'col_data_quality', type_='foreignkey')
    op.drop_constraint(None, 'col_data_quality', type_='foreignkey')
    op.create_foreign_key(op.f('col_data_quality_task_id_fkey'), 'col_data_quality', 'col_task', ['task_id'], ['id'])
    op.create_foreign_key(op.f('col_data_quality_meter_id_fkey'), 'col_data_quality', 'dev_meter', ['meter_id'], ['id'])
    op.drop_constraint('uq_data_quality', 'col_data_quality', type_='unique')
    op.drop_index(op.f('ix_col_data_quality_stat_date'), table_name='col_data_quality')
    # ### end Alembic commands ###
