"""add class_id attribute_id module to meter_point

Revision ID: 14399098fe8c
Revises: 66e93637ebea
Create Date: 2026-05-16 20:29:22.569769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14399098fe8c'
down_revision: Union[str, Sequence[str], None] = '66e93637ebea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable first, fill defaults, then set NOT NULL
    op.add_column('dev_meter_point', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('dev_meter_point', sa.Column('attribute_id', sa.Integer(), nullable=True))
    op.add_column('dev_meter_point', sa.Column('module', sa.String(length=50), nullable=True))

    # Fill existing rows with defaults
    op.execute("UPDATE dev_meter_point SET class_id = 1, attribute_id = 2, module = '' WHERE class_id IS NULL")

    # Now alter to NOT NULL
    op.alter_column('dev_meter_point', 'class_id', nullable=False)
    op.alter_column('dev_meter_point', 'attribute_id', nullable=False)
    op.alter_column('dev_meter_point', 'module', nullable=False, server_default='')

    # Update unique constraint to include attribute_id
    op.drop_constraint(op.f('uq_meter_point_obis'), 'dev_meter_point', type_='unique')
    op.create_unique_constraint('uq_meter_point_obis', 'dev_meter_point', ['meter_id', 'obis_code', 'attribute_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_meter_point_obis', 'dev_meter_point', type_='unique')
    op.create_unique_constraint(op.f('uq_meter_point_obis'), 'dev_meter_point', ['meter_id', 'obis_code'])
    op.drop_column('dev_meter_point', 'module')
    op.drop_column('dev_meter_point', 'attribute_id')
    op.drop_column('dev_meter_point', 'class_id')
    # ### end Alembic commands ###
