"""add meter reading and daily summary tables

Revision ID: 647db91bd8f6
Revises: dad61bb3e226
Create Date: 2026-05-16 11:04:13.142507

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '647db91bd8f6'
down_revision: Union[str, Sequence[str], None] = 'dad61bb3e226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('col_meter_reading',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('reading_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reading_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['dev_meter_point.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['col_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_col_meter_reading_meter_id'), 'col_meter_reading', ['meter_id'], unique=False)
    op.create_index(op.f('ix_col_meter_reading_point_id'), 'col_meter_reading', ['point_id'], unique=False)
    op.create_index(op.f('ix_col_meter_reading_reading_time'), 'col_meter_reading', ['reading_time'], unique=False)
    op.create_table('col_reading_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('max_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('first_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('last_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('reading_count', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['point_id'], ['dev_meter_point.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_col_reading_daily_meter_id'), 'col_reading_daily', ['meter_id'], unique=False)
    op.create_index(op.f('ix_col_reading_daily_point_id'), 'col_reading_daily', ['point_id'], unique=False)
    op.create_index(op.f('ix_col_reading_daily_stat_date'), 'col_reading_daily', ['stat_date'], unique=False)
    # Clear old meter_point data before schema change
    op.execute("DELETE FROM dev_meter_point")
    op.add_column('dev_meter_point', sa.Column('meter_id', sa.Integer(), nullable=False))
    op.add_column('dev_meter_point', sa.Column('obis_code', sa.String(length=30), nullable=False))
    op.add_column('dev_meter_point', sa.Column('scaler', sa.Integer(), server_default='0', nullable=False))
    op.add_column('dev_meter_point', sa.Column('is_collectible', sa.Boolean(), server_default='true', nullable=False))
    op.drop_constraint(op.f('dev_meter_point_point_code_key'), 'dev_meter_point', type_='unique')
    op.create_index(op.f('ix_dev_meter_point_meter_id'), 'dev_meter_point', ['meter_id'], unique=False)
    op.create_index(op.f('ix_dev_meter_point_obis_code'), 'dev_meter_point', ['obis_code'], unique=False)
    op.create_foreign_key(None, 'dev_meter_point', 'dev_meter', ['meter_id'], ['id'])
    op.drop_column('dev_meter_point', 'point_code')
    op.drop_column('dev_meter_point', 'protocol')
    op.drop_column('dev_meter_point', 'storage_target')
    op.drop_column('dev_meter_point', 'retention_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dev_meter_point', sa.Column('retention_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('dev_meter_point', sa.Column('storage_target', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('dev_meter_point', sa.Column('protocol', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('dev_meter_point', sa.Column('point_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dev_meter_point', type_='foreignkey')
    op.drop_index(op.f('ix_dev_meter_point_obis_code'), table_name='dev_meter_point')
    op.drop_index(op.f('ix_dev_meter_point_meter_id'), table_name='dev_meter_point')
    op.create_unique_constraint(op.f('dev_meter_point_point_code_key'), 'dev_meter_point', ['point_code'])
    op.drop_column('dev_meter_point', 'is_collectible')
    op.drop_column('dev_meter_point', 'scaler')
    op.drop_column('dev_meter_point', 'obis_code')
    op.drop_column('dev_meter_point', 'meter_id')
    op.drop_index(op.f('ix_col_reading_daily_stat_date'), table_name='col_reading_daily')
    op.drop_index(op.f('ix_col_reading_daily_point_id'), table_name='col_reading_daily')
    op.drop_index(op.f('ix_col_reading_daily_meter_id'), table_name='col_reading_daily')
    op.drop_table('col_reading_daily')
    op.drop_index(op.f('ix_col_meter_reading_reading_time'), table_name='col_meter_reading')
    op.drop_index(op.f('ix_col_meter_reading_point_id'), table_name='col_meter_reading')
    op.drop_index(op.f('ix_col_meter_reading_meter_id'), table_name='col_meter_reading')
    op.drop_table('col_meter_reading')
    # ### end Alembic commands ###
