"""add collection session table

Revision ID: 66e93637ebea
Revises: 131a05b9332f
Create Date: 2026-05-16 18:53:35.575351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e93637ebea'
down_revision: Union[str, Sequence[str], None] = '131a05b9332f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('col_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('mongo_db', sa.String(length=200), nullable=False),
    sa.Column('mongo_collection', sa.String(length=200), nullable=False),
    sa.Column('mongo_doc_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_read', sa.Integer(), nullable=False),
    sa.Column('total_success', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('sheet_count', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('communication', sa.String(length=20), nullable=False),
    sa.Column('meter_ip', sa.String(length=50), nullable=False),
    sa.Column('ping_status', sa.Boolean(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['dev_project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['col_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='采集会话表（PG-MongoDB 桥梁）'
    )
    op.create_index(op.f('ix_col_session_meter_id'), 'col_session', ['meter_id'], unique=False)
    op.create_index(op.f('ix_col_session_status'), 'col_session', ['status'], unique=False)
    op.create_index('ix_session_meter_time', 'col_session', ['meter_id', 'started_at'], unique=False)
    op.create_index('ix_session_project_time', 'col_session', ['project_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_session_project_time', table_name='col_session')
    op.drop_index('ix_session_meter_time', table_name='col_session')
    op.drop_index(op.f('ix_col_session_status'), table_name='col_session')
    op.drop_index(op.f('ix_col_session_meter_id'), table_name='col_session')
    op.drop_table('col_session')
    # ### end Alembic commands ###
