"""add col_data_quality table

Revision ID: dad61bb3e226
Revises: 295492b06f34
Create Date: 2026-05-16 10:11:49.407422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad61bb3e226'
down_revision: Union[str, Sequence[str], None] = '295492b06f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('col_data_quality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('success_points', sa.Integer(), nullable=False),
    sa.Column('failed_points', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('abnormal_count', sa.Integer(), nullable=False),
    sa.Column('first_collect_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_collect_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['col_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_col_data_quality_meter_id'), 'col_data_quality', ['meter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_col_data_quality_meter_id'), table_name='col_data_quality')
    op.drop_table('col_data_quality')
    # ### end Alembic commands ###
