"""init_all_tables

Revision ID: f6f96096b187
Revises: 
Create Date: 2026-05-16 02:21:43.702491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f96096b187'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_meter_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('point_code', sa.String(length=50), nullable=False),
    sa.Column('point_name', sa.String(length=100), nullable=False),
    sa.Column('point_type', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('storage_target', sa.String(length=20), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_code')
    )
    op.create_table('dev_meter_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dev_wire_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_alarm_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('point_code', sa.String(length=50), nullable=False),
    sa.Column('condition_config', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_data_archive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('archive_type', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('archive_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sys_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('leader', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sys_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('sys_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['sys_department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_user_username'), 'sys_user', ['username'], unique=True)
    op.create_table('col_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=False),
    sa.Column('execution_content', sa.JSON(), nullable=False),
    sa.Column('filter_config', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_execute_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_execute_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dev_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_lead_id', sa.Integer(), nullable=True),
    sa.Column('dev_lead_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dev_lead_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['test_lead_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sys_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_audit_log_operation_type'), 'sys_audit_log', ['operation_type'], unique=False)
    op.create_index(op.f('ix_sys_audit_log_user_id'), 'sys_audit_log', ['user_id'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_table('col_task_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_devices', sa.Integer(), nullable=False),
    sa.Column('success_devices', sa.Integer(), nullable=False),
    sa.Column('failed_devices', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['col_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_col_task_log_task_id'), 'col_task_log', ['task_id'], unique=False)
    op.create_table('dev_meter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('meter_name', sa.String(length=100), nullable=False),
    sa.Column('meter_type_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('hardware_version', sa.String(length=50), nullable=False),
    sa.Column('frame_number', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('current_status', sa.String(length=20), nullable=False),
    sa.Column('factory_date', sa.Date(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['meter_type_id'], ['dev_meter_type.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['dev_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_meter_current_status'), 'dev_meter', ['current_status'], unique=False)
    op.create_index(op.f('ix_dev_meter_serial_number'), 'dev_meter', ['serial_number'], unique=True)
    op.create_table('lab_test_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['dev_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('col_task_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('data_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['col_task_log.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['col_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_col_task_device_log_id'), 'col_task_device', ['log_id'], unique=False)
    op.create_index(op.f('ix_col_task_device_meter_id'), 'col_task_device', ['meter_id'], unique=False)
    op.create_index(op.f('ix_col_task_device_task_id'), 'col_task_device', ['task_id'], unique=False)
    op.create_table('dev_meter_attachment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_meter_attachment_meter_id'), 'dev_meter_attachment', ['meter_id'], unique=False)
    op.create_table('dev_meter_borrow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.Column('borrow_reason', sa.String(length=200), nullable=False),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('dept_approver_id', sa.Integer(), nullable=True),
    sa.Column('lab_approver_id', sa.Integer(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['borrower_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['dept_approver_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['lab_approver_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_meter_borrow_meter_id'), 'dev_meter_borrow', ['meter_id'], unique=False)
    op.create_table('dev_meter_comm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('connection_type', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('device_address', sa.String(length=50), nullable=False),
    sa.Column('baud_rate', sa.Integer(), nullable=False),
    sa.Column('parity', sa.String(length=10), nullable=False),
    sa.Column('data_bits', sa.Integer(), nullable=False),
    sa.Column('stop_bits', sa.Integer(), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id')
    )
    op.create_table('dev_meter_repair',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('repaired_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['repaired_by'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_meter_repair_meter_id'), 'dev_meter_repair', ['meter_id'], unique=False)
    op.create_table('dev_meter_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('online_status', sa.Boolean(), nullable=False),
    sa.Column('last_comm_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_strength', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=20), nullable=False),
    sa.Column('stack_usage', sa.Integer(), nullable=True),
    sa.Column('eeprom_write_count', sa.Integer(), nullable=True),
    sa.Column('last_data_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_id')
    )
    op.create_table('dev_meter_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=20), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_meter_status_meter_id'), 'dev_meter_status', ['meter_id'], unique=False)
    op.create_table('lab_defect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_defect_test_id'), 'lab_defect', ['test_id'], unique=False)
    op.create_table('lab_test_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('test_type', sa.String(length=50), nullable=False),
    sa.Column('test_environment', sa.String(length=200), nullable=False),
    sa.Column('test_duration_days', sa.Integer(), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('hardware_version', sa.String(length=50), nullable=False),
    sa.Column('conclusion', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['lab_test_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_number'),
    sa.UniqueConstraint('test_id')
    )
    op.create_table('sys_alarm_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meter_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('alarm_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alarm_message', sa.Text(), nullable=False),
    sa.Column('alarm_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('is_handled', sa.Boolean(), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['handled_by'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['dev_meter.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['sys_alarm_rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_alarm_record_is_handled'), 'sys_alarm_record', ['is_handled'], unique=False)
    op.create_index(op.f('ix_sys_alarm_record_meter_id'), 'sys_alarm_record', ['meter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_alarm_record_meter_id'), table_name='sys_alarm_record')
    op.drop_index(op.f('ix_sys_alarm_record_is_handled'), table_name='sys_alarm_record')
    op.drop_table('sys_alarm_record')
    op.drop_table('lab_test_report')
    op.drop_index(op.f('ix_lab_defect_test_id'), table_name='lab_defect')
    op.drop_table('lab_defect')
    op.drop_index(op.f('ix_dev_meter_status_meter_id'), table_name='dev_meter_status')
    op.drop_table('dev_meter_status')
    op.drop_table('dev_meter_snapshot')
    op.drop_index(op.f('ix_dev_meter_repair_meter_id'), table_name='dev_meter_repair')
    op.drop_table('dev_meter_repair')
    op.drop_table('dev_meter_comm')
    op.drop_index(op.f('ix_dev_meter_borrow_meter_id'), table_name='dev_meter_borrow')
    op.drop_table('dev_meter_borrow')
    op.drop_index(op.f('ix_dev_meter_attachment_meter_id'), table_name='dev_meter_attachment')
    op.drop_table('dev_meter_attachment')
    op.drop_index(op.f('ix_col_task_device_task_id'), table_name='col_task_device')
    op.drop_index(op.f('ix_col_task_device_meter_id'), table_name='col_task_device')
    op.drop_index(op.f('ix_col_task_device_log_id'), table_name='col_task_device')
    op.drop_table('col_task_device')
    op.drop_table('lab_test_task')
    op.drop_index(op.f('ix_dev_meter_serial_number'), table_name='dev_meter')
    op.drop_index(op.f('ix_dev_meter_current_status'), table_name='dev_meter')
    op.drop_table('dev_meter')
    op.drop_index(op.f('ix_col_task_log_task_id'), table_name='col_task_log')
    op.drop_table('col_task_log')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_audit_log_user_id'), table_name='sys_audit_log')
    op.drop_index(op.f('ix_sys_audit_log_operation_type'), table_name='sys_audit_log')
    op.drop_table('sys_audit_log')
    op.drop_table('dev_project')
    op.drop_table('col_task')
    op.drop_index(op.f('ix_sys_user_username'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_table('sys_role_permission')
    op.drop_table('sys_role')
    op.drop_table('sys_permission')
    op.drop_table('sys_department')
    op.drop_table('sys_data_archive')
    op.drop_table('sys_alarm_rule')
    op.drop_table('dev_wire_type')
    op.drop_table('dev_meter_type')
    op.drop_table('dev_meter_point')
    # ### end Alembic commands ###
